version: '3'
services:
  web:
    build: src/
    command: bundle exec ruby app.rb
    ports:
      - "4567:4567"
    links:
      - redis
    networks:
      - tinynet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6-alpine
    networks:
      - tinynet

networks:
  tinynet:
